title: "omkar – Law Student"
description: "Thoughts on law, legal research, and my professional journey."
baseurl: "" # leave empty for <username>.github.io
url: "https://<your-username>.github.io"
markdown: kramdown
theme: minimal-mistakes-jekyll

# Navigation bar – adjust order as you like
header_pages:
  - index.md
  - blog.md
  - cv.md
  - contact.md

# Author info (appears on posts & sidebar)
author:
  name: "Omkar"
  avatar: "/assets/images/avatar.jpg"
  bio: "LL.B. candidate, University of XYZ, interested in constitutional law and human rights."
  location: "City, Country"
  email: "you@example.com"
